name: Build and Test

on:
  push:
    branches-ignore:
      - main # Ignore pushes to the main branch
    # Optionally, target specific branches if needed:
    # branches:
        - codespace-humble-rotary-phone-69975ggv667vhrvv
    #   - feature/**

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        # Optionally, checkout a specific branch if needed (though 'on: push' usually handles this)
        # with:
        #   ref: ${{ github.ref_name }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python manage.py test
